//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejercicio1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblEvento> tblEventos { get; set; }
        public virtual DbSet<tblGuerra> tblGuerras { get; set; }
    
        public virtual int ppInsertEvento(Nullable<int> codigoGuerra, Nullable<int> tipoEvento, string descripcion, Nullable<System.DateTime> fechaEvento, Nullable<int> cantidadMuertos, Nullable<int> cantidadHeridos)
        {
            var codigoGuerraParameter = codigoGuerra.HasValue ?
                new ObjectParameter("CodigoGuerra", codigoGuerra) :
                new ObjectParameter("CodigoGuerra", typeof(int));
    
            var tipoEventoParameter = tipoEvento.HasValue ?
                new ObjectParameter("TipoEvento", tipoEvento) :
                new ObjectParameter("TipoEvento", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var fechaEventoParameter = fechaEvento.HasValue ?
                new ObjectParameter("FechaEvento", fechaEvento) :
                new ObjectParameter("FechaEvento", typeof(System.DateTime));
    
            var cantidadMuertosParameter = cantidadMuertos.HasValue ?
                new ObjectParameter("CantidadMuertos", cantidadMuertos) :
                new ObjectParameter("CantidadMuertos", typeof(int));
    
            var cantidadHeridosParameter = cantidadHeridos.HasValue ?
                new ObjectParameter("CantidadHeridos", cantidadHeridos) :
                new ObjectParameter("CantidadHeridos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ppInsertEvento", codigoGuerraParameter, tipoEventoParameter, descripcionParameter, fechaEventoParameter, cantidadMuertosParameter, cantidadHeridosParameter);
        }
    
        public virtual int ppUpsertGuerra(Nullable<int> codigoGuerra, string pais1, string pais2, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string paisGanador, Nullable<int> cantidadMuertos, Nullable<int> cantidadPresos, Nullable<decimal> perdidaFinanciera, string estadoGuerra, Nullable<int> heridos)
        {
            var codigoGuerraParameter = codigoGuerra.HasValue ?
                new ObjectParameter("CodigoGuerra", codigoGuerra) :
                new ObjectParameter("CodigoGuerra", typeof(int));
    
            var pais1Parameter = pais1 != null ?
                new ObjectParameter("Pais1", pais1) :
                new ObjectParameter("Pais1", typeof(string));
    
            var pais2Parameter = pais2 != null ?
                new ObjectParameter("Pais2", pais2) :
                new ObjectParameter("Pais2", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var paisGanadorParameter = paisGanador != null ?
                new ObjectParameter("PaisGanador", paisGanador) :
                new ObjectParameter("PaisGanador", typeof(string));
    
            var cantidadMuertosParameter = cantidadMuertos.HasValue ?
                new ObjectParameter("CantidadMuertos", cantidadMuertos) :
                new ObjectParameter("CantidadMuertos", typeof(int));
    
            var cantidadPresosParameter = cantidadPresos.HasValue ?
                new ObjectParameter("CantidadPresos", cantidadPresos) :
                new ObjectParameter("CantidadPresos", typeof(int));
    
            var perdidaFinancieraParameter = perdidaFinanciera.HasValue ?
                new ObjectParameter("PerdidaFinanciera", perdidaFinanciera) :
                new ObjectParameter("PerdidaFinanciera", typeof(decimal));
    
            var estadoGuerraParameter = estadoGuerra != null ?
                new ObjectParameter("EstadoGuerra", estadoGuerra) :
                new ObjectParameter("EstadoGuerra", typeof(string));
    
            var heridosParameter = heridos.HasValue ?
                new ObjectParameter("Heridos", heridos) :
                new ObjectParameter("Heridos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ppUpsertGuerra", codigoGuerraParameter, pais1Parameter, pais2Parameter, fechaInicioParameter, fechaFinParameter, paisGanadorParameter, cantidadMuertosParameter, cantidadPresosParameter, perdidaFinancieraParameter, estadoGuerraParameter, heridosParameter);
        }
    }
}
