//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejercicio1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvento
    {
        public int Id { get; set; }
        public int CodigoGuerra { get; set; }
        public int TipoEvento { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaIngreso { get; set; } = DateTime.Now;
        public System.DateTime FechaEvento { get; set; } = DateTime.Now;
        public int CantidadMuertos { get; set; }
        public int CantidadHeridos { get; set; }
    }
}
