//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejercicio_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Infidelidade
    {
        public int Id { get; set; }
        public string NombreAfectado { get; set; }
        public string ApellidosAfectado { get; set; }
        public string NombreInfiel { get; set; }
        public string ApellidosInfiel { get; set; }
        public string SexoInfiel { get; set; }
        public string SexoAfectado { get; set; }
        public DateTime FechaEvento { get; set; }
        public DateTime FechaIngreso { get; set ; }
        public string EstadoPareja { get; set; }
        public bool EsLaPrimeraVez { get; set; }
        
        public string RetornarDatos()
        {
            //return every attribute in this class
            return "Id de la infidelidad: " + this.Id + "\n" +
                "--------------------------------------" + "\n" +
                "Nombre del Afectado: " + this.NombreAfectado + "\n" +
                "Apellidos del Afectado: " + this.ApellidosAfectado + "\n" +
                "Nombre del Infiel: " + this.NombreInfiel + "\n" +
                "Apellidos del Infiel: " + this.ApellidosInfiel + "\n" +
                "Sexo del Infiel: " + this.SexoInfiel + "\n" +
                "Sexo del Afectado: " + this.SexoAfectado + "\n" +
                "Fecha del Evento: " + this.FechaEvento.ToShortDateString() + "\n" +
                "Fecha de Ingreso: " + this.FechaIngreso.ToString() + "\n" +
                "Estado de la Pareja: " + this.EstadoPareja + "\n" +
                "Es La Primera Vez?: " + ( this.EsLaPrimeraVez ? "Si" : "No") + "\n";
        }

    }
   
}
