//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio6Consola.WS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblVerdugo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class tblVerdugo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        private System.DateTime FNacimientoField;
        
        private System.DateTime FEventoField;
        
        private System.DateTime FRegistroField;
        
        private int CantidadHijosField;
        
        private bool VivoField;
        
        private bool PresoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((this.TipoDocumentoField.Equals(value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime FNacimiento {
            get {
                return this.FNacimientoField;
            }
            set {
                if ((this.FNacimientoField.Equals(value) != true)) {
                    this.FNacimientoField = value;
                    this.RaisePropertyChanged("FNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime FEvento {
            get {
                return this.FEventoField;
            }
            set {
                if ((this.FEventoField.Equals(value) != true)) {
                    this.FEventoField = value;
                    this.RaisePropertyChanged("FEvento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime FRegistro {
            get {
                return this.FRegistroField;
            }
            set {
                if ((this.FRegistroField.Equals(value) != true)) {
                    this.FRegistroField = value;
                    this.RaisePropertyChanged("FRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int CantidadHijos {
            get {
                return this.CantidadHijosField;
            }
            set {
                if ((this.CantidadHijosField.Equals(value) != true)) {
                    this.CantidadHijosField = value;
                    this.RaisePropertyChanged("CantidadHijos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public bool Vivo {
            get {
                return this.VivoField;
            }
            set {
                if ((this.VivoField.Equals(value) != true)) {
                    this.VivoField = value;
                    this.RaisePropertyChanged("Vivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool Preso {
            get {
                return this.PresoField;
            }
            set {
                if ((this.PresoField.Equals(value) != true)) {
                    this.PresoField = value;
                    this.RaisePropertyChanged("Preso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS.ServicioLab6Soap")]
    public interface ServicioLab6Soap {
        
        // CODEGEN: Generating message contract since element name descripcion from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarVerdugo", ReplyAction="*")]
        Laboratorio6Consola.WS.RegistrarVerdugoResponse RegistrarVerdugo(Laboratorio6Consola.WS.RegistrarVerdugoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarVerdugo", ReplyAction="*")]
        System.Threading.Tasks.Task<Laboratorio6Consola.WS.RegistrarVerdugoResponse> RegistrarVerdugoAsync(Laboratorio6Consola.WS.RegistrarVerdugoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarVerdugoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarVerdugo", Namespace="http://tempuri.org/", Order=0)]
        public Laboratorio6Consola.WS.RegistrarVerdugoRequestBody Body;
        
        public RegistrarVerdugoRequest() {
        }
        
        public RegistrarVerdugoRequest(Laboratorio6Consola.WS.RegistrarVerdugoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarVerdugoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Laboratorio6Consola.WS.tblVerdugo verdugo;
        
        public RegistrarVerdugoRequestBody() {
        }
        
        public RegistrarVerdugoRequestBody(string descripcion, Laboratorio6Consola.WS.tblVerdugo verdugo) {
            this.descripcion = descripcion;
            this.verdugo = verdugo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarVerdugoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarVerdugoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Laboratorio6Consola.WS.RegistrarVerdugoResponseBody Body;
        
        public RegistrarVerdugoResponse() {
        }
        
        public RegistrarVerdugoResponse(Laboratorio6Consola.WS.RegistrarVerdugoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarVerdugoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Laboratorio6Consola.WS.Respuesta RegistrarVerdugoResult;
        
        public RegistrarVerdugoResponseBody() {
        }
        
        public RegistrarVerdugoResponseBody(Laboratorio6Consola.WS.Respuesta RegistrarVerdugoResult) {
            this.RegistrarVerdugoResult = RegistrarVerdugoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioLab6SoapChannel : Laboratorio6Consola.WS.ServicioLab6Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioLab6SoapClient : System.ServiceModel.ClientBase<Laboratorio6Consola.WS.ServicioLab6Soap>, Laboratorio6Consola.WS.ServicioLab6Soap {
        
        public ServicioLab6SoapClient() {
        }
        
        public ServicioLab6SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioLab6SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioLab6SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioLab6SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laboratorio6Consola.WS.RegistrarVerdugoResponse Laboratorio6Consola.WS.ServicioLab6Soap.RegistrarVerdugo(Laboratorio6Consola.WS.RegistrarVerdugoRequest request) {
            return base.Channel.RegistrarVerdugo(request);
        }
        
        public Laboratorio6Consola.WS.Respuesta RegistrarVerdugo(string descripcion, Laboratorio6Consola.WS.tblVerdugo verdugo) {
            Laboratorio6Consola.WS.RegistrarVerdugoRequest inValue = new Laboratorio6Consola.WS.RegistrarVerdugoRequest();
            inValue.Body = new Laboratorio6Consola.WS.RegistrarVerdugoRequestBody();
            inValue.Body.descripcion = descripcion;
            inValue.Body.verdugo = verdugo;
            Laboratorio6Consola.WS.RegistrarVerdugoResponse retVal = ((Laboratorio6Consola.WS.ServicioLab6Soap)(this)).RegistrarVerdugo(inValue);
            return retVal.Body.RegistrarVerdugoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laboratorio6Consola.WS.RegistrarVerdugoResponse> Laboratorio6Consola.WS.ServicioLab6Soap.RegistrarVerdugoAsync(Laboratorio6Consola.WS.RegistrarVerdugoRequest request) {
            return base.Channel.RegistrarVerdugoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laboratorio6Consola.WS.RegistrarVerdugoResponse> RegistrarVerdugoAsync(string descripcion, Laboratorio6Consola.WS.tblVerdugo verdugo) {
            Laboratorio6Consola.WS.RegistrarVerdugoRequest inValue = new Laboratorio6Consola.WS.RegistrarVerdugoRequest();
            inValue.Body = new Laboratorio6Consola.WS.RegistrarVerdugoRequestBody();
            inValue.Body.descripcion = descripcion;
            inValue.Body.verdugo = verdugo;
            return ((Laboratorio6Consola.WS.ServicioLab6Soap)(this)).RegistrarVerdugoAsync(inValue);
        }
    }
}
