//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio6
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVerdugo
    {
        public int Id { get; set; }
        public int TipoDocumento { get; set; }
        public string Documento { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public System.DateTime FNacimiento { get; set; }
        public System.DateTime FEvento { get; set; }
        public System.DateTime FRegistro { get; set; }
        public int CantidadHijos { get; set; }
        public bool Vivo { get; set; }
        public bool Preso { get; set; }
    }
}
