//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio10
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSolicitante
    {
        public int Id { get; set; }
        public string TipoDocumento { get; set; }
        public string Documento { get; set; }
        public Nullable<System.DateTime> FNacimiento { get; set; }
        public Nullable<System.DateTime> FIngreso { get; set; }
        public string Estado { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Direccion { get; set; }
        public string EstadoCivil { get; set; }
        public string AprobadoEsposo { get; set; }
    }
}
